// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using System.Xml;
using System.Collections.Generic;

namespace AssemblyCSharp
{
    public class PlayerPrefsEx
    {
        Dictionary<string, int> status_int;
        Dictionary<string, string> status_string;

        /// <summary>
        /// コンストラクタ
        /// </summary>
        public PlayerPrefsEx()
        {
            status_int = new Dictionary<string, int>();
            status_string = new Dictionary<string, string>();
        }

        /// <summary>
        /// Int型の値を保持する
        /// </summary>
        /// <param name="key">Keyの値</param>
        /// <param name="val">保存する値</param>
        public void SetInt(string key, int val)
        {
            if (status_int.ContainsKey(key))
            {
                status_int[key] = val;
            }
            else
            {
                status_int.Add(key, val);
            }
        }

        /// <summary>
        /// String型の値を保持する
        /// </summary>
        /// <param name="key">Keyの値</param>
        /// <param name="val">保存する値</param>
        public void SetString(string key, string val)
        {
            if (status_string.ContainsKey(key))
            {
                status_string[key] = val;
            }
            else
            {
                status_string.Add(key, val);
            }
        }

        /// <summary>
        /// データをセーブする
        /// </summary>
        /// <param name="path">セーブする場所</param>
        public void Save(string path)
        {
            //ドキュメントのインスタンス生成
            XmlDocument document = new XmlDocument();
            //XML宣言/親宣言 + 追加
            XmlDeclaration declaration = document.CreateXmlDeclaration("1.0", "UTF-8", null);
            XmlElement root = document.CreateElement("root");
            document.AppendChild(declaration);
            document.AppendChild(root);
            //要素（子）追加（string）
            foreach (var val in status_string)
            {
                XmlElement KVKey = document.CreateElement("key");
                KVKey.InnerText = val.Key;
                XmlElement KVValue = document.CreateElement("string");
                KVValue.InnerText = val.Value.ToString();

                root.AppendChild(KVKey);
                root.AppendChild(KVValue);
            }
            //要素（子）追加（int）
            foreach(var val in status_int)
            {
             XmlElement KVKey = document.CreateElement("key");
                KVKey.InnerText = val.Key;
             XmlElement KVValue = document.CreateElement("integer");
                KVValue.InnerText = val.Value.ToString();

             root.AppendChild(KVKey);
             root.AppendChild(KVValue);
            }
            
            //ファイル出力
            document.Save(path);
        }

        /// <summary>
        /// 指定したセーブデータをロードする
        /// </summary>
        /// <param name="path">セーブデータのファイルパス</param>
        public void Load(string path)
        {
            XmlDocument document = new XmlDocument();
            document.Load(path);
            string KVKey="";
            foreach (XmlElement elem in document.DocumentElement)
            {
                if (elem.Name == "key")
                {
                    KVKey = elem.InnerText;
                }
                else if (elem.Name == "integer")
                {
                    if (status_int.ContainsKey(KVKey))
                    {
                        status_int[KVKey] = int.Parse(elem.InnerText);
                    }
                    else
                    {
                        status_int.Add(KVKey, int.Parse(elem.InnerText));
                    }
                }
                else if (elem.Name == "string")
                {
                    if (status_int.ContainsKey(KVKey))
                    {
                        status_string[KVKey] = elem.InnerText;
                    }
                    else
                    {
                        status_string.Add(KVKey, elem.InnerText);
                    }
                }
            }
        }

        /// <summary>
        /// Keyとなる値からint値を取得する
        /// </summary>
        /// <returns>The int.</returns>
        /// <param name="key">Keyとなる値</param>
        public int GetInt(string key)
        {
            return status_int[key];
        }

        /// <summary>
        /// Keyとなる値からstring値を取得する
        /// </summary>
        /// <returns>The int.</returns>
        /// <param name="key">Keyとなる値</param>
        public string GetString(string key)
        {
            return status_string[key];
        }
    }
}

